### PR TITLE
feat:add theme switch

### PR DESCRIPTION
**Pull request by SHUAXINDIARY**
light、dark and Follow System Theme

### CODE REVIEW

**Comment by SHUAXINDIARY** [comment]
Adding this function is to find that when the background is set to a rounded rectangle and a right-angle rectangle, and when the background of the profile photo is light, the distinction between the two is not obvious

**Comment by SHUAXINDIARY** [comment]
At the same time, I think the dark theme is cool😎

**Comment by wwayne** [comment]
@SHUAXINDIARY  Thanks :) I will do merging
Seems the Sass compiler complained about this [line](https://github.com/chilllab/react-nice-avatar/pull/18/files#diff-6ef96599d3541c9598dea37a0665658957f7c8d1cdf0ef392269dd6412dae2e4R399)
I will do a quick fix and add a theme toggle button this weekend

**Comment by SHUAXINDIARY** [comment]
> @SHUAXINDIARY Thanks :) I will do merging
> Seems the Sass compiler complained about this [line](https://github.com/chilllab/react-nice-avatar/pull/18/files#diff-6ef96599d3541c9598dea37a0665658957f7c8d1cdf0ef392269dd6412dae2e4R399)
> I will do a quick fix and add a theme toggle button this weekend

Sorry, I didn't test the package, but I already fixed it and mentioned another pr

**Comment by wwayne** [comment]
Thanks :) merging

**Pull request merged**
